# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canpian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qly_id', models.PositiveIntegerField(verbose_name='\u672c\u5730\u7f16\u53f7')),
                ('name', models.CharField(max_length=60, verbose_name='\u540d\u79f0')),
                ('weight', models.FloatField(help_text='\u5355\u4f4d\u514b', verbose_name='\u91cd\u91cf')),
                ('diameter', models.FloatField(help_text='\u5355\u4f4d\u5398\u7c73', verbose_name='\u76f4\u5f84')),
                ('thickness', models.FloatField(help_text='\u5355\u4f4d\u6beb\u7c73', verbose_name='\u539a\u5ea6')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
                ('completeness', models.CharField(choices=[('complete', '\u5b8c\u6574'), ('incomplete', '\u6b8b\u7f3a')], default='incomplete', max_length=10, verbose_name='\u662f\u5426\u5b8c\u6574')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u94dc\u955c\u6b8b\u7247',
                'verbose_name_plural': '\u94dc\u955c\u6b8b\u7247',
            },
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('start_year', models.SmallIntegerField(verbose_name='\u5f00\u59cb\u5e74\u4efd')),
                ('end_year', models.SmallIntegerField(verbose_name='\u7ec8\u6b62\u5e74\u4efd')),
            ],
            options={
                'verbose_name': '\u5e74\u4ee3',
                'verbose_name_plural': '\u5e74\u4ee3',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/', verbose_name='File')),
                ('canpian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='canpian.Canpian')),
            ],
        ),
        migrations.AddField(
            model_name='canpian',
            name='dynasty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canpian.Dynasty', verbose_name='\u5e74\u4ee3'),
        ),
    ]
